### ISSUE TITLE
Building with Mono?

### ISSUE THREAD

**Issue by dwminer** [blahlicus/arbites-family#1]
I've been trying to build this for Windows [7] using the latest version of Mono - `xbuild ArbitesR.csproj` or so. It builds but crashes on launch every time. (I've built against both the current master and release 1.0.) Is there something I'm doing wrong or is Mono compatibility currently broken?

Thanks for any help.

**Comment by blahlicus** [comment]
Hey,

You need to build to `Debug` or copy the contents of `bin/Debug` (the `keygroups` directory and `keyboards` directory inside `bin/Debug`) to your desired build location as they contain dependencies for the application.

An example command that would `xbuild` a working version is the following command:

`xbuild /p:Configuration=Debug ArbitesR.csproj`

Just curious, but why are you compiling with mono on windows 7?

Cheers

Blahlicus

**Comment by dwminer** [comment]
I had been using it on Linux, so I went with what I knew. I'll probably move to a more 'native' toolset if I end up playing with the code more though, yeah...

Anyway, that seems to be what was missing. Thanks!
