### ISSUE TITLE
Is it possible to create a dead key layout?

### ISSUE THREAD

**Issue by thshdw** [blahlicus/arbites-family#24]
Would it be possible to trigger another layer using a dead key? 
Pressing ```,``` for example would trigger the layer and pressing ```g``` makes a ```{``` 
Once this happens it goes back to the main layer. 

This way I don't have to hold a key or toggle a key to trigger the layer.

**Comment by blahlicus** [comment]
Hey, you can't exactly do that but there's a pretty similar feature, in the sticky keys.

Assign a key to stickyFN1`, then place `{` to layer1 of `g`, pressing the sticky key, then pressing `g` would output `{`.

**Comment by thshdw** [comment]
Thanks. What happens after the ```{``` output is complete? Is the sticky key still in its state or would I be back at my main layer?

**Comment by blahlicus** [comment]
You would be back at your main layer, the sticky modifiers only work for one key, after that you are returned to your main layer.

**Comment by thshdw** [comment]
Thanks. This answered my question.
