### ISSUE TITLE
Newly added layers after LoadLayout shows up with empty buttons

### ISSUE THREAD

**Issue by accidentalrebel** [blahlicus/arbites-family#3]
This is for ArbitesEto.

If a newly loaded layout has more layers than the current number of displayed layers, the loaded layout appears with just blank buttons.

![image](https://cloud.githubusercontent.com/assets/1009214/15581656/d90a0882-239f-11e6-8ae3-8d0e8d545218.png)
_Layers 3 onwards should have data as dictated by the data loaded by the given .uk2dm_

## To reproduce:
1. Click "Select Device"
2. Click "diverge-tm.uktb"
  - _At this point, 3 layers can be seen on the screen_
3. Click "Load Layout"
4. Select a .uk2dm layout with more than 3 layers. 
  - You can use [mine](https://gist.github.com/accidentalrebel/0bf2520d5f17774f8d68583285421e89).
5. Notice that layers 0-2 has their buttons filled. 3 and 4 layers display nulls even though there should be data.

## Workaround:
1. Know in advance the number of layers that the .uk2dm to be loaded will require
2. Press "Add New Layer" button until you have the correct number of layers
3. Load the .uk2dm layout

Thanks!

**Comment by blahlicus** [comment]
Yep, confirmed, I'll fix it right now.

**Comment by blahlicus** [comment]
fixed, will be included in release 1.3 (due sunday)

see [commit](https://github.com/blahlicus/arbites-family/commit/fcbfa9c3b4479c41f5fe0c90dcb87809d4855c63).
