### ISSUE TITLE
looking for other key combinations

### ISSUE THREAD

**Issue by rclasen** [blahlicus/arbites-family#4]
Hi,

not sure if this is the right way to ask for help (or raise a feature request). Please point me at a better way if this is inappropriate.

I'm missing the following functionality to port my existing qmk / ergodox layout to animus/arbites/diverge3:

- a layer key that toggles on tap and temporarily switches to layer when hold down / combined with other key
- one key that sends LALT on hold and ESC on tap
- one key that acts as LCTRL+LALT+LWIN
- one key that sends ctrl on hold and space on tap
- mouse keys

Is there a way to achieve this with existing versions?

thanks,
 Rainer

**Comment by blahlicus** [comment]
Animus already has all the function you've listed, I am currently in the progress of getting the configuration tools ready for that in Arbites as well, should be up in a few days.

**Comment by rclasen** [comment]
Ah, great.
thanks for getting back that quickly.

**Comment by leothelocust** [comment]
Are mouse keys available now? I didn't see them in the key selection window.
