### ISSUE TITLE
Dual-role Cmd/Win

### ISSUE THREAD

**Issue by quarterto** [blahlicus/arbites-family#5]
As a Mac user, a dual-role command key would be more useful to me that ctrl/alt/etc. Is there any way to map such a key? Perhaps with a custom keygroup (I can't find any examples of this though).

**Comment by blahlicus** [comment]
Animus itself does not have this function at the moment, it is only capable of dual-roles with shift, alt, altgr, ctrl, and fn keys, I'll have that added to the next iteration of Animus,

I have created a new issue for that at the animus repo, please refer to [this issue](https://github.com/blahlicus/animus-family/issues/11) from now on, I'll close this issue now.
