### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by leothelocust** [blahlicus/arbites-family#7]
@blahlicus Great work!

I saw a few things that I would like to help out with. Namely the Wiki for now, but eventually, I wouldn't mind assisting with the rest if I am able.

In order to update the wiki tho, it looks like I need to be a collaborator? or maybe just you need to give me permission?

Looking forward to helping!
\- Levi

**Comment by leothelocust** [comment]
I know you're busy @blahlicus but I would like to help out with the wiki if you wouldn't mind.

**Comment by blahlicus** [comment]
Hey, sure thing, I'll just give you collaborator access to this repo, I'm too busy to look at PRs on a separate wiki repo at the moment so I'll not do that.
